Prep javascript variables
kelvin-lao-01/prep-0722-code-solutions pull request #11
Opened 2022-08-08 18:45 UTC by kelvin-lao-01

![Screen Shot 2022-08-08 at 11 42 50 AM](https://user-images.githubusercontent.com/48492707/183491177-ed52b051-978c-423c-971d-b14c6f8e927f.png)
![Screen Shot 2022-08-08 at 11 42 52 AM](https://user-images.githubusercontent.com/48492707/183491183-bb1b23b5-6fb4-4269-9b45-040de422bdd4.png)

2022-08-09 02:45 UTC, thebearingedge requested changes

2022-08-09 02:45 UTC, thebearingedge commented on prep-javascript-variables/index.html
> +    var nothing = 'null';
Hi Kelvin, be sure to leave off the quotes for your number, boolean, and null so that the JavaScript engine doesn't interpret them as strings.

2022-08-09 17:34 UTC, kelvin-lao-01 commented on prep-javascript-variables/index.html
> +    var nothing = 'null';
got it

2022-08-10 18:10 UTC, thebearingedge approved these changes

2023-03-21 16:25 UTC, closed without merging