Completed prep-javascript-conditionals exercise
kelvin-lao-01/prep-0722-code-solutions pull request #16
Opened 2022-08-10 21:34 UTC by kelvin-lao-01

![Screen Shot 2022-08-10 at 2 33 35 PM](https://user-images.githubusercontent.com/48492707/184024376-ea9dfaec-9116-447f-86d7-01fc07444ebe.png)

2022-08-11 00:25 UTC, thebearingedge requested changes

2022-08-11 00:25 UTC, thebearingedge commented on prep-javascript-conditionals/index.html
> +}
Hi Kelvin, you'll need some `else if` blocks in here so that scores like 70 or 80 don't get turned into A++. 

```js
if (student2Score < 60) {

} else if (student2Score < 70) {

} else if (student2Score < 80) {

// etc etc
```

2022-08-12 18:42 UTC, thebearingedge requested changes

2022-08-12 18:42 UTC, thebearingedge commented on prep-javascript-conditionals/index.html
> +console.log(student2Score);
Hi Kelvin, try combining these into one `if ... else if ... else` "ladder"

https://web1.eng.famu.fsu.edu/~haik/met.dir/hcpp.dir/notes.dir/cppnotes/node41.html#:~:text=A%20common%20programming%20construct%20that,of%20the%20ladder%20is%20bypassed.

2022-08-12 18:42 UTC, thebearingedge commented on prep-javascript-conditionals/index.html
> +console.log(season);
This part too, try combining it into one `if ... else if ... else` ladder.

2022-08-14 17:06 UTC, kelvin-lao-01 commented on prep-javascript-conditionals/index.html
> +}
![Screen Shot 2022-08-14 at 10 06 17 AM](https://user-images.githubusercontent.com/48492707/184547490-8b9ffe55-8703-410f-88e9-476bdf9ea6a5.png)

2022-08-15 22:40 UTC, thebearingedge requested changes

2022-08-15 22:40 UTC, thebearingedge commented on prep-javascript-conditionals/index.html
> +console.log(student2Score);
Hi Kelvin, try combining all of these in to one set of `if ... else if ... else`

```js
// partial example

if (student2Score < 60) {
  console.log('F');
} else if (student2Score < 70) {
  console.log('D');
} ... {
} else {
  console.log('A++');
}

```

You should have `else if` statements for each level of grade between `'F'` and `'A++'`.

2022-08-15 22:40 UTC, thebearingedge commented on prep-javascript-conditionals/index.html
> +console.log(season);
Like mentioned above for the student score, try combining these all.

2022-08-16 04:41 UTC, kelvin-lao-01 commented on prep-javascript-conditionals/index.html
> +console.log(season);
just saw this, got it

2022-08-16 05:28 UTC, kelvin-lao-01 commented
<img width="569" alt="Screen Shot 2022-08-15 at 10 18 41 PM" src="https://user-images.githubusercontent.com/48492707/184804105-a8121c29-d6aa-47c0-83ea-7fcbf0c11351.png">
<img width="548" alt="Screen Shot 2022-08-15 at 10 18 57 PM" src="https://user-images.githubusercontent.com/48492707/184804109-bfab74ec-24d3-4cba-9fbb-949cc44ccabe.png">

Okay I have updated the studen2score with else if / else + logging. I have also updated the seasons with else & if + logging. Since its just referring to seasons I wasn't sure if it needed an else if since its pretty straight forward based on what the assignment was asking in regards to the seasons matching. Please let me know if there's anything else I need to change.

2022-08-17 02:35 UTC, thebearingedge requested changes
continued conversation in Slack regarding combining all of the if / else if / else checks for the different possible grades

2022-08-17 12:48 UTC, thebearingedge approved these changes

2023-03-21 16:24 UTC, closed without merging